DROP TABLE IF EXISTS estoque_setor;

-- Fonte da verdade: append-only.
CREATE TABLE IF NOT EXISTS evento_do_estoque (
    sequencia  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id  VARCHAR(160)  NOT NULL,
    versao     BIGINT        NOT NULL,
    tipo       VARCHAR(40)   NOT NULL,
    dados      VARCHAR(2000) NOT NULL,
    gravado_em TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_evento_do_estoque_stream_versao UNIQUE (stream_id, versao)
);

CREATE INDEX IF NOT EXISTS ix_evento_do_estoque_stream
    ON evento_do_estoque (stream_id, versao);

-- Memoria de entrega do broker.
CREATE TABLE IF NOT EXISTS evento_processado (
    evento_id     VARCHAR(36) PRIMARY KEY,
    processado_em TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Projecoes
CREATE TABLE IF NOT EXISTS disponibilidade_por_setor (
    evento     VARCHAR(80) NOT NULL,
    setor      VARCHAR(50) NOT NULL,
    capacidade INT NOT NULL,
    retirados  INT NOT NULL,
    disponivel INT NOT NULL,
    PRIMARY KEY (evento, setor)
);

CREATE TABLE IF NOT EXISTS projecao_checkpoint (
    projecao         VARCHAR(60) PRIMARY KEY,
    ultima_sequencia BIGINT NOT NULL
);
